### PR TITLE
Updated the Inno Setup version from 6.1.2 to 6.2.0

### PR DESCRIPTION
**Pull request by Lakritzator**

### CODE REVIEW

**Comment by vslavik** [comment]
Thanks, but the change unfortunately didn't update the scripts to account for 6.2's updated graphics files (see the failing build).

**Comment by Lakritzator** [comment]
It wasn't really clear what changes we needed, let me check if I can find what is needed. I assumed is just a version increase, as it's only a minor, so wrong...

**Comment by vslavik** [comment]
It's all right, that's what CI is for. From https://jrsoftware.org/files/is6-whatsnew.htm, Jordan changed some graphics, so a breakage on a bitmap file corresponds to that:

> [Setup] section directives WizardImageFile and WizardSmallImageFile now default to a blank value which makes Setup use new built-in wizard images. To use the old wizard images again set WizardImageFile and WizardSmallImageFile to compiler:WizClassicImage.bmp and compiler:WizClassicSmallImage.bmp respectively.

Looking at the *Checks* tab of this PR, the build even reports which files were installed by the IS installer:
```
-a---            5/8/2021 12:00 AM          26494 WizClassicImage.bmp
-a---            5/8/2021 12:00 AM          52574 WizClassicImage-IS.bmp
-a---            5/8/2021 12:00 AM           1658 WizClassicSmallImage.bmp
-a---            5/8/2021 12:00 AM           4158 WizClassicSmallImage-IS.bmp
```

So I think it's as simple as removing the other bitmaps from our script...

**Comment by Lakritzator** [comment]
What about using wild-cards for most of the files, so we just get them no matter if they are renamed or not?

More or less replace the whole nuspec file entries with something like this:

```
    <files>
        <file src="license.txt" target="" />
        <file src="README.md" target="" />
        <file src="Tools.InnoSetup.props" target="build" />
        <file src="inst\*.*" exclude="unins000.*" target="tools" />
        <file src="inst\Languages\*.isl" target="tools\Languages" />
        <file src="inst\Languages\*.islu" target="tools\Languages" />
    </files>
```

**Comment by vslavik** [comment]
> What about using wild-cards for most of the files, so we just get them no matter if they are renamed or not?

You're right, this definitely makes sense.

> \<file src="inst\*.*" exclude="unins000.*" target="tools" />

I also exclude `Compil32.exe` (the GUI) now, but that's not important and arguably may make sense to include anyway…

>  \<file src="inst\Languages\*.islu" target="tools\Languages" />

Another simplification: *.islu files don't exist anymore, only *.isl

**Comment by vslavik** [comment]
Merged now. Thanks a lot!

**Pull request merged**
